"""
Global constants
================

.. currentmodule:: sctools

This module contains global constants, such as various barcoded BAM tags, and sctools-specific
constants.
"""

RAW_SAMPLE_BARCODE_TAG_KEY = 'SR'
QUALITY_SAMPLE_BARCODE_TAG_KEY = 'SY'

MOLECULE_BARCODE_TAG_KEY = 'UB'
RAW_MOLECULE_BARCODE_TAG_KEY = 'UR'
QUALITY_MOLECULE_BARCODE_TAG_KEY = 'UY'

CELL_BARCODE_TAG_KEY = 'CB'
RAW_CELL_BARCODE_TAG_KEY = 'CR'
QUALITY_CELL_BARCODE_TAG_KEY = 'CY'

GENE_NAME_TAG_KEY = 'GE'
NUMBER_OF_HITS_TAG_KEY = 'NH'

ALIGNMENT_LOCATION_TAG_KEY = 'XF'
INTRONIC_ALIGNMENT_LOCATION_TAG_VALUE = 'INTRONIC'
CODING_ALIGNMENT_LOCATION_TAG_VALUE = 'CODING'
UTR_ALIGNMENT_LOCATION_TAG_VALUE = 'UTR'
INTERGENIC_ALIGNMENT_LOCATION_TAG_VALUE = 'INTERGENIC'
